# Generated by Django 4.2.4 on 2023-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landmark", "0004_alter_landmark_imgfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="imgfile",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
